services:
  - type: web
    name: websec-scanner
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 2 --threads 4 --timeout 300 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.0
